##### Que. What is Numpy?
* Ans. Numpy - Numerical Python
* Numpy - is a python package used for computation and processing of single dimension and multi dimensional array elements.
* Numpy was created by merging the features of ancestor modules, Numeric and Numarray, of Numpy.
* It is an extended module of Python mainly written in C.
* Numpy provides various functions which are capable of performing many numeric computation with High speed.
* Numpy provides various Data Structues, implemnting multi-dimensional arrays and matrices.
* These Data Structures are used for optimal computation regarding arrays and matrices.

##### Que. By whom & when Numpy was created?
Ans. Travis Oliphant created Numpy in the year 2005.

##### Que. What are the various Data Analysis Libraries?
##### Ans. The various Data Analysis libraries are:-
    - Numpy
    - Pandas
    - Matplotlib
    - SciPy etc.
    
##### Que. Why Python is first choice language for Data Scientist?
Ans. There are various reasons why Python is first choice language for Data Scientist. Few of them are:-
######    1. Python is simple & easy to learn.
######    2. Syntaxes are simple
######    3. Comes with batteries included
######    4. etc.
    
Que. Why do we need Numpy?
* Ans. Numpy is a Python library which provides convenient and efficient way to handle large amount of Data and is also very convenient with matrix multiplication and Data reshaping. 
* Being fast, makes it reasonable to work with huge data.
* Numpy in collaboration with SciPy and Matplotlib, used as a replacement to MATLAB as Python is more complete and easier programming language.

Que. What are the advantages of using Numpy?
Ans. The advantages of using Numpy are:-
    1. Numpy performs array-oriented computation.
    2. It efficiently implements the multidimensional arrays.
    3. It perfomrs scientific computation.
    4. It is capable of perfomring Fourier Transform and reshaping the data stored in multidimensional array.
    5. Numpy provides the in-built functions for linear algebra and random number generation.
    
Numpy Installation:-
    1. For windows user and using command prompt or not using Anaconda or using some other editor:-
        Open command prompt and type "pip install Numpy" and wait for it to download and install.
    2. For Mac user and using terminal or not using Anaconda or using some other editor:-
        Open terminal and type "sudo apt-get install python-Numpy" and wait for it to download and install.
    3. For Windows or Mac user and using Anaconda Python:-
        No need to install anything as Anaconda comes with all data analytics tools and packages installed in advance.


## Creating Numpy Arrays

In [3]:
# !pip install numpy -- upgrade

In [4]:
 import numpy as np

#### 1. Create an array with python list or tuple using array function

In [7]:
lst = [1,3,5,7,9]
lst

[1, 3, 5, 7, 9]

In [8]:
type(lst)

list

In [9]:
arr = np.array(lst)
arr

array([1, 3, 5, 7, 9])

In [13]:
# Checking the type of an array - ndarray stands for n-dimensional array

type(arr)

numpy.ndarray

#### This is an one dimensional array

In [12]:
# Checking the size of an array - size attribute returns no. of elements in an array
arr.size

5

In [20]:
# Checking the shape of an array - shape attribute returns no. rows vs columns
arr.shape


(5,)

In [19]:
# Checking the dimensiona of an array - ndim returns the dimensiona of an array
arr.ndim

1

#### Creating a multi-dimensional array from a multi-dimensional list

In [14]:
 lst1 = [[2,4,6,8],[3,6,9,12]]

In [15]:
arr2 = np.array(lst1)
arr2

array([[ 2,  4,  6,  8],
       [ 3,  6,  9, 12]])

#### This is a two dimensional array.

In [21]:
# Checking the size of an array - size attribute returns no. of elements in an array
arr2.size

8

In [22]:
# Checking the shape of an array - shape attribute returns no. rows vs columns
arr2.shape


(2, 4)

In [25]:
# Checking the dimensiona of an array - ndim returns the dimension of an array
arr2.ndim

2

#### 2. Create an array with an arange function

<b>arange</b> : Like the built-in range but returns an ndarray instead of a list.

In [26]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [27]:
np.arange(1,8)

array([1, 2, 3, 4, 5, 6, 7])

In [28]:
np.arange(3,20,3)

array([ 3,  6,  9, 12, 15, 18])

#### Using reshape to create n dimensional arrays

In [29]:
np.arange(10).reshape(5,2)

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

for arange ( 10 ), the possible combinations for reshape are (2,5), (5,2), (1,10)

In [30]:
np.arange(10).reshape(1,10)

array([[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]])

#### arange() function also accepts float arguments

In [37]:
arr_of_floats = np.arange(0, 10, 0.5)
arr_of_floats

# 0.2 is step size - difference between 2 consecutive element is 0.2

array([0. , 0.5, 1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5, 5. , 5.5, 6. ,
       6.5, 7. , 7.5, 8. , 8.5, 9. , 9.5])

#### 3. Create an array with an linespace function

In [34]:
np.linspace(1,10,50)

# 20 is num which is used for number of samples to generate

array([ 1.        ,  1.18367347,  1.36734694,  1.55102041,  1.73469388,
        1.91836735,  2.10204082,  2.28571429,  2.46938776,  2.65306122,
        2.83673469,  3.02040816,  3.20408163,  3.3877551 ,  3.57142857,
        3.75510204,  3.93877551,  4.12244898,  4.30612245,  4.48979592,
        4.67346939,  4.85714286,  5.04081633,  5.2244898 ,  5.40816327,
        5.59183673,  5.7755102 ,  5.95918367,  6.14285714,  6.32653061,
        6.51020408,  6.69387755,  6.87755102,  7.06122449,  7.24489796,
        7.42857143,  7.6122449 ,  7.79591837,  7.97959184,  8.16326531,
        8.34693878,  8.53061224,  8.71428571,  8.89795918,  9.08163265,
        9.26530612,  9.44897959,  9.63265306,  9.81632653, 10.        ])

When you want to generate a specific number of elements within a given range then use linspace() whereas if you want to generate a seq of equally spaced values then use arange() function.

#### 4. Create an array with zeros,ones,empty and eye function

creates an array of 0's with the given shape. zeros_like takes another array and produces a 0's array of same shape and dtype.

In [38]:
np.zeros((5,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [40]:
np.zeros_like([[1,2,3,4,5],[6,7,8,9,0]])

array([[0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]])

creates an array of 1's with the given shape. ones_like takes another array and produces a 1's array of same shape and dtype.

In [20]:
# creating a 2D array of specified shape, shape shuld be provided in tuple
np.ones((3,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [21]:
# creating a 3D array of specified shape, shape shuld be provided in tuple
np.ones( ( 3,5,6 ) )

array([[[1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.]]])

#### Here three dimensional 5*6 (maticices) arrays has been created.

In [43]:
np.empty((3,4))

array([[ 2.31584178e+077, -2.68679245e+154,  5.92878775e-323,
         0.00000000e+000],
       [ 1.47763627e+248,  5.30276956e+180,  1.57076922e-076,
         4.57576052e-071],
       [ 4.26127172e-086,  3.35659829e-143,  6.01433264e+175,
         6.93885958e+218]])

####  np.eye() creates an identity matrix. eye, identity : Create a square N x N identity matrix (1’s on the diagonal and 0’s elsewhere

In [23]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

  #### 5. Create an array with random.rand function

In [24]:
np.random.rand(3,1)

array([[0.22001789],
       [0.72552284],
       [0.55642481]])

In [25]:
np.floor(10*np.random.rand(2,4))

array([[7., 9., 9., 9.],
       [9., 5., 8., 7.]])

In [ ]:
dict([i for i in enumerate([1, 0, 1 , 0, 2, 0, 1, 0, 0, 1, 0]) if i[-1] != 0])

In [2]:
list(enumerate([1, 0, 1 , 0, 2, 0, 1, 0, 0, 1, 0]))

[(0, 1),
 (1, 0),
 (2, 1),
 (3, 0),
 (4, 2),
 (5, 0),
 (6, 1),
 (7, 0),
 (8, 0),
 (9, 1),
 (10, 0)]