## Reshaping

In [2]:
import numpy as np

reshape() gives a new shape to an array without changing its data

In [2]:
a = np.arange(6)
a

array([0, 1, 2, 3, 4, 5])

In [3]:
a.shape

(6,)

In [4]:
a.reshape(2,3)

array([[0, 1, 2],
       [3, 4, 5]])

In [5]:
 b = np.arange(20).reshape(4,5)
 b

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

##### The reshape() dimensions needs to match the number of values in the array
Reshaping a 15-element array to an 18-element one will throw an error

In [6]:
b.reshape(5,4)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19]])

In [7]:
np.arange(15).reshape(3,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

#### Specify only one dimension (and infer the others) when reshaping
Another way we can reshape is by metioning only one dimension, and -1. -1 means that the length in that dimension is inferred

In [8]:
Asian_countries = np.array(["India","Pakistan",
                            "China","Japan",
                            "Sri Lanka","Thailand",
                            "Bangladesh","Myanmar"])
Asian_countries

array(['India', 'Pakistan', 'China', 'Japan', 'Sri Lanka', 'Thailand',
       'Bangladesh', 'Myanmar'], dtype='<U10')

#### Here the unspecified value is inferred to be 2

In [9]:
Asian_countries.reshape(-1,4) 

array([['India', 'Pakistan', 'China', 'Japan'],
       ['Sri Lanka', 'Thailand', 'Bangladesh', 'Myanmar']], dtype='<U10')

#### Here the unspecified value is inferred to be 3

In [10]:
Asian_countries.reshape(2,-1)

array([['India', 'Pakistan', 'China', 'Japan'],
       ['Sri Lanka', 'Thailand', 'Bangladesh', 'Myanmar']], dtype='<U10')

#### If the values of the dimensions are not factors of the number of elements, there will be an error

In [11]:
Asian_countries.reshape(3,-1)

ValueError: cannot reshape array of size 8 into shape (3,newaxis)

### T gives transpose of an array

In [3]:
a2 = np.arange(18).reshape(6,3)
a2

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14],
       [15, 16, 17]])

In [4]:
a2.T.ravel()

array([ 0,  3,  6,  9, 12, 15,  1,  4,  7, 10, 13, 16,  2,  5,  8, 11, 14,
       17])

### The ravel() function
The primary functional difference is that flatten is a method of an ndarray object and hence can only be called for true numpy arrays. In contrast ravel() is a library-level function and hence can be called on any object that can successfully be parsed. For example ravel() will work on a list of ndarrays, while flatten will not.

In [14]:
Asian_countries.ravel()

array(['India', 'Pakistan', 'China', 'Japan', 'Sri Lanka', 'Thailand',
       'Bangladesh', 'Myanmar'], dtype='<U10')

### C - like index ordering

In [15]:
a1 = np.arange(8)
a1

array([0, 1, 2, 3, 4, 5, 6, 7])

In [16]:
np.reshape(a1,(2,4))

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

#### C-like indexing ordering is equivalent C reshape and C ravel

In [17]:
np.reshape(np.ravel(a1),(2,4))

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

### Forton - like indexing ordering

In [18]:
np.reshape(a1, (2, 4), order ='F')

array([[0, 2, 4, 6],
       [1, 3, 5, 7]])

NameError: name 'numpy' is not defined