## Arithmatic operators on arrays apply elementwise

In [1]:
import numpy as np

In [2]:
a = np.array([10,20,30,40])
b = np.array ([5,10,15,20])

In [3]:
a+b

array([15, 30, 45, 60])

In [4]:
a-b

array([ 5, 10, 15, 20])

In [5]:
a/b

array([2., 2., 2., 2.])

In [6]:
a**3

array([ 1000,  8000, 27000, 64000])

In [7]:
a%30

array([10, 20,  0, 10])

In [8]:
a<30

array([ True,  True, False, False])

In [9]:
a>30

array([False, False, False,  True])

### The product operator * operates elementwise multiplication in NumPy arrays.

In [10]:
a*b

array([ 50, 200, 450, 800])

### Dot function or method
The matrix product can be performed using the dot function or method.


In [11]:
A = np.array([[1,6],[6,7]]) 

B = np.array ([[2,4],[6,8]])

print ('A:\n', A)
print ('B:\n', B)

A:
 [[1 6]
 [6 7]]
B:
 [[2 4]
 [6 8]]


### Matrix product

In [12]:
A.dot(B)

array([[38, 52],
       [54, 80]])

#### Another matrix product

In [13]:
np.dot(A,B)

array([[38, 52],
       [54, 80]])

### Operations to  modify an existing array rather than create a new one

In [14]:
X = np.array([2,4,6])
Y = np.array([3,5,10])

In [15]:
X *= 2
X

array([ 4,  8, 12])

In [16]:
X += Y
X

array([ 7, 13, 22])

## Uses of unary operations
    
  

In [17]:
array_a = np.array([21,10,15,20])

### Computing the sum of all elements

In [18]:
array_a.sum() 

66

### Finding out the element having minimum value

In [19]:
array_a.min()

10

### Finding out the element having maximum value

In [20]:
array_a.max()

21

By default, these operations apply to the array as though it were a list of numbers, regardless of its shape. However,
by specifying the axis parameter you can apply an operation along the specified axis of an array.

In [21]:
num = np.arange(24).reshape(4,6)
num

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23]])

#### Row and column operations
In a 2D array axis #0 represents columns. Axis #1 refers to rows

### Sum up each column

In [22]:
num.sum(axis = 1)

array([ 15,  51,  87, 123])

### Sum up each row

In [23]:
num.min(axis = 1)

array([ 0,  6, 12, 18])

### Minimum of each row

In [24]:
num.min(axis = 1) 

array([ 0,  6, 12, 18])

### Maximum of each row

In [25]:
num.max(axis = 0)

array([18, 19, 20, 21, 22, 23])