## Indexing and Slicing

Indexing can be done in numpy by using an array as an index. A Python slice object is constructed by giving start, stop, and step parameters to the built-in slice function.

## One-dimensional array indexing

In [1]:
import numpy as np

In [2]:
a = np.arange(5)**2
a

array([ 0,  1,  4,  9, 16])

In [3]:
a[2]

4

In [4]:
a[-2]

9

## One-dimensional array slicing

In [5]:
a[2:5]

array([ 4,  9, 16])

In [6]:
a[:4:2]

array([0, 4])

In [7]:
a[:4:2] = -100
a

array([-100,    1, -100,    9,   16])

In [8]:
a[::-1]

array([  16,    9, -100,    1, -100])

In [9]:
a

array([-100,    1, -100,    9,   16])

## Two dimensional array indexing

In [10]:
b = np.arange(6).reshape(2,3)
b

array([[0, 1, 2],
       [3, 4, 5]])

In [11]:
b[1]

array([3, 4, 5])

In [12]:
b[1][1]

4

In [13]:
b[1,1]

4

### Compare with indexing of a list of lists

In [14]:
c = [[0,1,2],[3,4,5]]
c

[[0, 1, 2], [3, 4, 5]]

In [15]:
c[1]

[3, 4, 5]

In [16]:
c[1][1]

4

-  C [ 1 , 1 ] do not work here

In [17]:
c[1,1]

TypeError: list indices must be integers or slices, not tuple

## Two-dimensional array slicing

In [18]:
a1 = np.arange(25).reshape(5,5)
a1

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [19]:
a1[1,2:4]

array([7, 8])

In [20]:
a1[3:,3:]

array([[18, 19],
       [23, 24]])

In [21]:
a1[:,1]

array([ 1,  6, 11, 16, 21])

In [22]:
a1[::2,2::2]

array([[ 2,  4],
       [12, 14],
       [22, 24]])

## Fancy indexing with Arrays of integers

Boolean arrays used as indices are treated in a different manner entirely than index arrays. Boolean arrays must be of the same shape as the initial dimensions of the array being indexed. 

In [23]:
x = np.arange(5)**2
x

array([ 0,  1,  4,  9, 16])

Suppose we want to access three different elements. We could do it like this:

In [24]:
z = x[2],x[0],x[4]
z

(4, 0, 16)

In [25]:
type(z)

tuple

In [26]:
y = np.array ([3,1,3,0])
y

array([3, 1, 3, 0])

Here the the x is the data array and the y is index array. The shape is determined by the data array and the index is determined by the index array.

In [27]:
x[y]

array([9, 1, 9, 0])

In [28]:
x1 = np.array ([[0,3],[2,1]])
x1

array([[0, 3],
       [2, 1]])

In [29]:
y[x1]

array([[3, 0],
       [3, 1]])

Data array

In [30]:
fruit = np.array([["Banana","Mango","Guava","Avacado"],
            ["Papaya","Jack fruit","Plum","Strawberry"],
            ["Apricot","Apple","Blue berry","Black berry"]])
fruit

array([['Banana', 'Mango', 'Guava', 'Avacado'],
       ['Papaya', 'Jack fruit', 'Plum', 'Strawberry'],
       ['Apricot', 'Apple', 'Blue berry', 'Black berry']], dtype='<U11')

Index array

In [31]:
k = np.array([[0,1],[1,2]])
k

array([[0, 1],
       [1, 2]])

Index array

In [32]:
v = np.array([[2,1],[3,3]])
v

array([[2, 1],
       [3, 3]])

k is for row indexing and v is for column indexing

In [33]:
fruit[k,v]

array([['Guava', 'Jack fruit'],
       ['Strawberry', 'Black berry']], dtype='<U11')

### Modifying Values with Fancy Indexing

By the following way new values can be assigned using indexing.

In [34]:
fruit[k,v] = "Potato"
fruit

array([['Banana', 'Mango', 'Potato', 'Avacado'],
       ['Papaya', 'Potato', 'Plum', 'Potato'],
       ['Apricot', 'Apple', 'Blue berry', 'Potato']], dtype='<U11')

## Fancy indexing with boolean Array

In [35]:
g = np.arange(12).reshape(3,4)
g

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

Now we find the elements that are greater than 6. This will return a numpy array of the same shape as our original array. 

In [36]:
h = g > 6
h

array([[False, False, False, False],
       [False, False, False,  True],
       [ True,  True,  True,  True]])

In [37]:
g[h]

array([ 7,  8,  9, 10, 11])

We can do all of the above in a single concise statement.

In [38]:
print(g[g > 6])

[ 7  8  9 10 11]


### Counting 

#### How many values less than 6?

In [39]:
np.sum(g < 6)

6

This operation can be showen by the following way:

In [40]:
np.count_nonzero(g < 6)

6

#### How many values less than 6 in each row?

In [41]:
np.sum(g < 6, axis=1)

array([4, 2, 0])

#### How many values less than 6 in each column?

In [42]:
np.sum(g < 6, axis=0)

array([2, 2, 1, 1])

#### Are there any values greater than 8?

In [43]:
np.any(g > 8)

True

#### Are all values less than 10?

In [44]:
np.all(g < 10)

False