## ArrayBroadCasting

### The Basiscs
-  Broadcasting is the way used by NumPy when dealing with arrays of different shapes during arithmatic operations.


### General Broadcasting Rules
When operating on two arrays, NumPy compares their shapes element-wise. The dimensions are considered in reverse order, starting with the trailing dimensions, and working its way forward. Two dimensions are compatible when

1) they are equal <br/>
2) one of them is of size 1

In [2]:
import numpy as np

In [2]:
a = np.arange(3)
a

array([0, 1, 2])

In [3]:
b = 100
b

100

b is streched horizontally and addition is taking place to each element with 100.

In [4]:
a + b

array([100, 101, 102])

#### Row wise broad casting

In [5]:
a = np.arange(6).reshape(2,3)
a

array([[0, 1, 2],
       [3, 4, 5]])

In [6]:
b = np.array([100,100,100])
b

array([100, 100, 100])

a is 2 by 3 array and b is 1 by 3 array. When this two are being added b get streched vertically and the addition takes place elementwise.

In [7]:
a + b

array([[100, 101, 102],
       [103, 104, 105]])

#### Column wise broad casting

In [8]:
a

array([[0, 1, 2],
       [3, 4, 5]])

In [9]:
b = np.array([0,1]).reshape(2,1)
b

array([[0],
       [1]])

a is 2 by 3 array and b is 3 by 1 array. When this two are being added b get streched horizontally and the addition takes place elementwise.

In [10]:
a + b

array([[0, 1, 2],
       [4, 5, 6]])

In [11]:
a

array([[0, 1, 2],
       [3, 4, 5]])

In [12]:
b = 2
b

2

Here b is just a integer. In this case b is streched both horizontally and vertically.

In [13]:
a + b

array([[2, 3, 4],
       [5, 6, 7]])

#### Broad casting in both direction

In [14]:
a = np.array([0,3]).reshape(2,1)
a

array([[0],
       [3]])

In [15]:
b = np.array([0,1,2])
b

array([0, 1, 2])

a is streched horizontally to match the size of b and b is streched vertically to match the size of a and the addition takes place element wise.

In [16]:
a + b

array([[0, 1, 2],
       [3, 4, 5]])

In [17]:
x = np.array([0,1,2,3,4])
y= np.array([10,10,10,10,10])

Here the multiplication is taking place element wise.

In [18]:
x * y

array([ 0, 10, 20, 30, 40])

In [6]:
np.arange(9).reshape(3,3) + np.array([1,2])

ValueError: operands could not be broadcast together with shapes (3,3) (2,) 