## Iterating

In [1]:
import numpy as np

#### Iterate through array elements

In [2]:
a = np.array([1,2,3,4,5])
for element in a:
    print(element)

1
2
3
4
5


 Multidimensional array

In [3]:
a1 = np.array([[1,2,3,4,5],
          [11,6,7,8,9]])
a1

array([[ 1,  2,  3,  4,  5],
       [11,  6,  7,  8,  9]])

In [4]:
for row in a1:
    print("Row",row)

Row [1 2 3 4 5]
Row [11  6  7  8  9]


## Iterate using nditer

In [5]:
a2 = np.arange(18).reshape(6,3)
a2

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14],
       [15, 16, 17]])

### Using normal for loop iteration

In [6]:
for row in a2:
    for l in row:
        print (l)

0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17


### For loop with flatten

In [7]:
 for F in a2.flatten():
         print (F)

0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17


## Iteration with ndtier

#### C style ordering

In [8]:
for i in np.nditer(a2, order = 'C'):
    print(i)

0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17


### Fortan style ordering

In [9]:
for x in np.nditer (a2, order='F'):
    print(x)
    

0
3
6
9
12
15
1
4
7
10
13
16
2
5
8
11
14
17


### external_loop

In [10]:
for x in np.nditer(a2, flags = ['external_loop'],order = 'F'):
    print (x)

[ 0  3  6  9 12 15]
[ 1  4  7 10 13 16]
[ 2  5  8 11 14 17]


### Modify array values while iterating


In [11]:
for x in np.nditer(a2, op_flags=['readwrite']):
    x[...] = x * x

In [12]:
a2

array([[  0,   1,   4],
       [  9,  16,  25],
       [ 36,  49,  64],
       [ 81, 100, 121],
       [144, 169, 196],
       [225, 256, 289]])

### Iterates two broadcastable arrays concurrently

In [13]:
b = np.arange(3, 15, 2).reshape(6,1)
b

array([[ 3],
       [ 5],
       [ 7],
       [ 9],
       [11],
       [13]])

In [14]:
for u, v in np.nditer([a2,b]):
    print (u,v)

0 3
1 3
4 3
9 5
16 5
25 5
36 7
49 7
64 7
81 9
100 9
121 9
144 11
169 11
196 11
225 13
256 13
289 13
