## Automatic Reshaping

In [1]:
import numpy as np

In [2]:
a = np.arange(32)
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31])

The above 'a' array need to be changed to 3D array. The automatic reshaping can be seen if we denote any dimension as -1.

We replace one dimension with -1. -1 means that length in the dimension can be anything as but it should be a divisor of the number of elements.

In [3]:
a.shape = 4, -1, 8
a

array([[[ 0,  1,  2,  3,  4,  5,  6,  7]],

       [[ 8,  9, 10, 11, 12, 13, 14, 15]],

       [[16, 17, 18, 19, 20, 21, 22, 23]],

       [[24, 25, 26, 27, 28, 29, 30, 31]]])

In [4]:
a.shape

(4, 1, 8)

In [5]:
a.shape = 2, 2, -2
a

array([[[ 0,  1,  2,  3,  4,  5,  6,  7],
        [ 8,  9, 10, 11, 12, 13, 14, 15]],

       [[16, 17, 18, 19, 20, 21, 22, 23],
        [24, 25, 26, 27, 28, 29, 30, 31]]])

It should be noticed that the dimensions should be divisor of total number of elements present in the array.

In [6]:
a.shape

(2, 2, 8)

Now trying to reshape with (-1). Results in to new shape is (32, )

In [7]:
a.reshape(-1)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31])

Now trying to reshape with (-1,1). The number of column has been provided but not the number of row.

In [8]:
a.reshape (-1,1)

array([[ 0],
       [ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10],
       [11],
       [12],
       [13],
       [14],
       [15],
       [16],
       [17],
       [18],
       [19],
       [20],
       [21],
       [22],
       [23],
       [24],
       [25],
       [26],
       [27],
       [28],
       [29],
       [30],
       [31]])

In [9]:
a.reshape(-1,4)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23],
       [24, 25, 26, 27],
       [28, 29, 30, 31]])

if we try to provide both of the dimension as unknown i.e new shapes as (-1,-1). it will throw an error.

In [10]:
a.reshape(-1,-1)

ValueError: can only specify one unknown dimension