In [1]:
import numpy as np

In [2]:
population_data = np.genfromtxt( ,usecols=1, 
                         delimiter=',',skip_header=1)

https://en.wikipedia.org/wiki/List_of_countries_by_population_(United_Nations)

In [3]:
population_data

array([   792.,   1300.,   1618.,   2910.,   4049.,   5177.,   6320.,
        11192.,  11359.,  11773.,  14909.,  17380.,  21729.,  25398.,
        31196.,  33400.,  34571.,  35446.,  37922.,  38695.,  40120.,
        49290.,  53127.,  55144.,  55345.,  55641.,  56480.,  61349.,
        61559.,  73925.,  76965.,  84287.,  94737., 102012., 104901.,
       105264., 105544., 107825., 108020., 109897., 116398., 160539.,
       164229., 165314., 178844., 196440., 204327., 253045., 276244.])

In [4]:
population_data.shape

(49,)

### argmax

Returns the indices of the maximum values along an axis

In [5]:
np.argmax(population_data)

48

In [6]:
population_data[48]

276244.0

### argmin

Returns the indicies of the minimum values along an axis

In [7]:
np.argmin(population_data)

0

In [8]:
population_data [0]

792.0

### argsort

Returns the indices that would sort an array.

In [9]:
np.argsort(population_data)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48])

In [10]:
np.argsort(population_data, kind = 'megasort')

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48])

In [11]:
population_data[np.argsort(population_data, kind = 'megasort')]

array([   792.,   1300.,   1618.,   2910.,   4049.,   5177.,   6320.,
        11192.,  11359.,  11773.,  14909.,  17380.,  21729.,  25398.,
        31196.,  33400.,  34571.,  35446.,  37922.,  38695.,  40120.,
        49290.,  53127.,  55144.,  55345.,  55641.,  56480.,  61349.,
        61559.,  73925.,  76965.,  84287.,  94737., 102012., 104901.,
       105264., 105544., 107825., 108020., 109897., 116398., 160539.,
       164229., 165314., 178844., 196440., 204327., 253045., 276244.])

In [12]:
greater_than_55000 = np.where(population_data>55000)

In [13]:
greater_than_55000

(array([23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39,
        40, 41, 42, 43, 44, 45, 46, 47, 48]),)

In [14]:
len(greater_than_55000[0])

26

In [15]:
population_data[[greater_than_55000]]

array([[ 55144.,  55345.,  55641.,  56480.,  61349.,  61559.,  73925.,
         76965.,  84287.,  94737., 102012., 104901., 105264., 105544.,
        107825., 108020., 109897., 116398., 160539., 164229., 165314.,
        178844., 196440., 204327., 253045., 276244.]])

### numpy.extract

Return the elements of an array that satisfy some condition.

In [16]:
condition = population_data > np.mean(population_data)

##### Use the condition in the extract function

In [17]:
np.extract(condition, population_data)

array([ 76965.,  84287.,  94737., 102012., 104901., 105264., 105544.,
       107825., 108020., 109897., 116398., 160539., 164229., 165314.,
       178844., 196440., 204327., 253045., 276244.])