## View

Viewing is just the another way of viewing the data of the array.

By slecting the slice of the original array, or also by changing the dtype ( or a combination of both). These different kinds of views are described below:

In [1]:
import numpy as np

## Slice views

This is the most common source of view creations in numpy.

In [2]:
a = np.arange(10)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [3]:
v1 = a[1:2]
v1

array([1])

In [4]:
a[1] = 2

In [5]:
v1

array([2])

In [6]:
v2 = a[1::3]
v2

array([2, 4, 7])

In [7]:
a[7] = 10

In [8]:
v2

array([ 2,  4, 10])

Numpy has <b> ndarray.view()</b> method which is a new array object that looks at the same data of the original array. Unlike the earlier case, change in dimensions of the new array doesn't change dimensions of the original.

This operation of using <b> ndarray.view() </b> is called <b> shallow copy or view </b>

In [9]:
c = np.arange(6).reshape(3,2)
c

array([[0, 1],
       [2, 3],
       [4, 5]])

In [10]:
print ('Array c:')
print (c)

Array c:
[[0 1]
 [2 3]
 [4 5]]


In [11]:
print ('Create view of c:')
x = c.view()
print (x)

Create view of c:
[[0 1]
 [2 3]
 [4 5]]
